/**
 * generated by Xtext 2.32.0
 */
package com.epistimis.uddl.ui.wizard;

import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.ui.wizard.template.AbstractFileTemplate;
import org.eclipse.xtext.ui.wizard.template.FileTemplate;
import org.eclipse.xtext.ui.wizard.template.IFileGenerator;

@FileTemplate(label = "Sample File", icon = "file_template.png", description = "Basic data model")
@SuppressWarnings("all")
public final class HelloWorldFile extends AbstractFileTemplate {
  @Override
  public void generateFiles(final IFileGenerator generator) {
    StringConcatenation _builder = new StringConcatenation();
    String _folder = this.getFolder();
    _builder.append(_folder);
    _builder.append("/");
    String _name = this.getName();
    _builder.append(_name);
    _builder.append(".uddl");
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("dm Name \"Description\"\t\t{");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    generator.generate(_builder, _builder_1);
  }
}
