/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conceptual Data Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.uddl.ConceptualDataModel#getElement <em>Element</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.ConceptualDataModel#getCdm <em>Cdm</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.uddl.UddlPackage#getConceptualDataModel()
 * @model
 * @generated
 */
public interface ConceptualDataModel extends UddlElement
{
  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.uddl.uddl.ConceptualElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference list.
   * @see com.epistimis.uddl.uddl.UddlPackage#getConceptualDataModel_Element()
   * @model containment="true"
   * @generated
   */
  EList<ConceptualElement> getElement();

  /**
   * Returns the value of the '<em><b>Cdm</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.uddl.uddl.ConceptualDataModel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cdm</em>' containment reference list.
   * @see com.epistimis.uddl.uddl.UddlPackage#getConceptualDataModel_Cdm()
   * @model containment="true"
   * @generated
   */
  EList<ConceptualDataModel> getCdm();

} // ConceptualDataModel
