/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conceptual Participant Path Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.uddl.ConceptualParticipantPathNode#getProjectedParticipant <em>Projected Participant</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.uddl.UddlPackage#getConceptualParticipantPathNode()
 * @model
 * @generated
 */
public interface ConceptualParticipantPathNode extends ConceptualPathNode
{
  /**
   * Returns the value of the '<em><b>Projected Participant</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projected Participant</em>' reference.
   * @see #setProjectedParticipant(ConceptualParticipant)
   * @see com.epistimis.uddl.uddl.UddlPackage#getConceptualParticipantPathNode_ProjectedParticipant()
   * @model
   * @generated
   */
  ConceptualParticipant getProjectedParticipant();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.uddl.ConceptualParticipantPathNode#getProjectedParticipant <em>Projected Participant</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Projected Participant</em>' reference.
   * @see #getProjectedParticipant()
   * @generated
   */
  void setProjectedParticipant(ConceptualParticipant value);

} // ConceptualParticipantPathNode
