/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conceptual Characteristic Path Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.uddl.ConceptualCharacteristicPathNode#getProjectedCharacteristic <em>Projected Characteristic</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.uddl.UddlPackage#getConceptualCharacteristicPathNode()
 * @model
 * @generated
 */
public interface ConceptualCharacteristicPathNode extends ConceptualPathNode
{
  /**
   * Returns the value of the '<em><b>Projected Characteristic</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projected Characteristic</em>' reference.
   * @see #setProjectedCharacteristic(ConceptualCharacteristic)
   * @see com.epistimis.uddl.uddl.UddlPackage#getConceptualCharacteristicPathNode_ProjectedCharacteristic()
   * @model
   * @generated
   */
  ConceptualCharacteristic getProjectedCharacteristic();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.uddl.ConceptualCharacteristicPathNode#getProjectedCharacteristic <em>Projected Characteristic</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Projected Characteristic</em>' reference.
   * @see #getProjectedCharacteristic()
   * @generated
   */
  void setProjectedCharacteristic(ConceptualCharacteristic value);

} // ConceptualCharacteristicPathNode
