/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.uddl.DataModel#getCdm <em>Cdm</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.DataModel#getLdm <em>Ldm</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.DataModel#getPdm <em>Pdm</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.uddl.UddlPackage#getDataModel()
 * @model
 * @generated
 */
public interface DataModel extends UddlElement
{
  /**
   * Returns the value of the '<em><b>Cdm</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.uddl.uddl.ConceptualDataModel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cdm</em>' containment reference list.
   * @see com.epistimis.uddl.uddl.UddlPackage#getDataModel_Cdm()
   * @model containment="true"
   * @generated
   */
  EList<ConceptualDataModel> getCdm();

  /**
   * Returns the value of the '<em><b>Ldm</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.uddl.uddl.LogicalDataModel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ldm</em>' containment reference list.
   * @see com.epistimis.uddl.uddl.UddlPackage#getDataModel_Ldm()
   * @model containment="true"
   * @generated
   */
  EList<LogicalDataModel> getLdm();

  /**
   * Returns the value of the '<em><b>Pdm</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.uddl.uddl.PlatformDataModel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pdm</em>' containment reference list.
   * @see com.epistimis.uddl.uddl.UddlPackage#getDataModel_Pdm()
   * @model containment="true"
   * @generated
   */
  EList<PlatformDataModel> getPdm();

} // DataModel
