/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Enumeration Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.uddl.LogicalEnumerationConstraint#getAllowedValue <em>Allowed Value</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalEnumerationConstraint()
 * @model
 * @generated
 */
public interface LogicalEnumerationConstraint extends LogicalConstraint
{
  /**
   * Returns the value of the '<em><b>Allowed Value</b></em>' reference list.
   * The list contents are of type {@link com.epistimis.uddl.uddl.LogicalEnumerationLabel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Allowed Value</em>' reference list.
   * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalEnumerationConstraint_AllowedValue()
   * @model
   * @generated
   */
  EList<LogicalEnumerationLabel> getAllowedValue();

} // LogicalEnumerationConstraint
