/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Measurement System Axis</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.uddl.LogicalMeasurementSystemAxis#getAxis <em>Axis</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.LogicalMeasurementSystemAxis#getDefaultValueTypeUnit <em>Default Value Type Unit</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.LogicalMeasurementSystemAxis#getConstraint <em>Constraint</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalMeasurementSystemAxis()
 * @model
 * @generated
 */
public interface LogicalMeasurementSystemAxis extends LogicalElement
{
  /**
   * Returns the value of the '<em><b>Axis</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Axis</em>' reference.
   * @see #setAxis(LogicalCoordinateSystemAxis)
   * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalMeasurementSystemAxis_Axis()
   * @model
   * @generated
   */
  LogicalCoordinateSystemAxis getAxis();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.uddl.LogicalMeasurementSystemAxis#getAxis <em>Axis</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Axis</em>' reference.
   * @see #getAxis()
   * @generated
   */
  void setAxis(LogicalCoordinateSystemAxis value);

  /**
   * Returns the value of the '<em><b>Default Value Type Unit</b></em>' reference list.
   * The list contents are of type {@link com.epistimis.uddl.uddl.LogicalValueTypeUnit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default Value Type Unit</em>' reference list.
   * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalMeasurementSystemAxis_DefaultValueTypeUnit()
   * @model
   * @generated
   */
  EList<LogicalValueTypeUnit> getDefaultValueTypeUnit();

  /**
   * Returns the value of the '<em><b>Constraint</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.uddl.uddl.LogicalMeasurementConstraint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint</em>' containment reference list.
   * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalMeasurementSystemAxis_Constraint()
   * @model containment="true"
   * @generated
   */
  EList<LogicalMeasurementConstraint> getConstraint();

} // LogicalMeasurementSystemAxis
