/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Enumeration Label</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalEnumerationLabel()
 * @model
 * @generated
 */
public interface LogicalEnumerationLabel extends UddlElement, LogicalEnumeratedBase
{
} // LogicalEnumerationLabel
