/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Value Type Unit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.uddl.LogicalValueTypeUnit#getValueType <em>Value Type</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.LogicalValueTypeUnit#getUnit <em>Unit</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.LogicalValueTypeUnit#getConstraint <em>Constraint</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalValueTypeUnit()
 * @model
 * @generated
 */
public interface LogicalValueTypeUnit extends LogicalElement
{
  /**
   * Returns the value of the '<em><b>Value Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Type</em>' reference.
   * @see #setValueType(LogicalValueType)
   * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalValueTypeUnit_ValueType()
   * @model
   * @generated
   */
  LogicalValueType getValueType();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.uddl.LogicalValueTypeUnit#getValueType <em>Value Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Type</em>' reference.
   * @see #getValueType()
   * @generated
   */
  void setValueType(LogicalValueType value);

  /**
   * Returns the value of the '<em><b>Unit</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' reference.
   * @see #setUnit(LogicalUnit)
   * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalValueTypeUnit_Unit()
   * @model
   * @generated
   */
  LogicalUnit getUnit();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.uddl.LogicalValueTypeUnit#getUnit <em>Unit</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' reference.
   * @see #getUnit()
   * @generated
   */
  void setUnit(LogicalUnit value);

  /**
   * Returns the value of the '<em><b>Constraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint</em>' containment reference.
   * @see #setConstraint(LogicalConstraint)
   * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalValueTypeUnit_Constraint()
   * @model containment="true"
   * @generated
   */
  LogicalConstraint getConstraint();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.uddl.LogicalValueTypeUnit#getConstraint <em>Constraint</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraint</em>' containment reference.
   * @see #getConstraint()
   * @generated
   */
  void setConstraint(LogicalConstraint value);

} // LogicalValueTypeUnit
