/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Reference Point</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.uddl.LogicalReferencePoint#getLandmark <em>Landmark</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.LogicalReferencePoint#getReferencePointPart <em>Reference Point Part</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalReferencePoint()
 * @model
 * @generated
 */
public interface LogicalReferencePoint extends UddlElement
{
  /**
   * Returns the value of the '<em><b>Landmark</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Landmark</em>' reference.
   * @see #setLandmark(LogicalLandmark)
   * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalReferencePoint_Landmark()
   * @model
   * @generated
   */
  LogicalLandmark getLandmark();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.uddl.LogicalReferencePoint#getLandmark <em>Landmark</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Landmark</em>' reference.
   * @see #getLandmark()
   * @generated
   */
  void setLandmark(LogicalLandmark value);

  /**
   * Returns the value of the '<em><b>Reference Point Part</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.uddl.uddl.LogicalReferencePointPart}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference Point Part</em>' containment reference list.
   * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalReferencePoint_ReferencePointPart()
   * @model containment="true"
   * @generated
   */
  EList<LogicalReferencePointPart> getReferencePointPart();

} // LogicalReferencePoint
