/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.epistimis.uddl.uddl.UddlPackage
 * @generated
 */
public interface UddlFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UddlFactory eINSTANCE = com.epistimis.uddl.uddl.impl.UddlFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Data Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Model</em>'.
   * @generated
   */
  DataModel createDataModel();

  /**
   * Returns a new object of class '<em>Include</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Include</em>'.
   * @generated
   */
  Include createInclude();

  /**
   * Returns a new object of class '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element</em>'.
   * @generated
   */
  UddlElement createUddlElement();

  /**
   * Returns a new object of class '<em>Conceptual Data Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Data Model</em>'.
   * @generated
   */
  ConceptualDataModel createConceptualDataModel();

  /**
   * Returns a new object of class '<em>Logical Data Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Data Model</em>'.
   * @generated
   */
  LogicalDataModel createLogicalDataModel();

  /**
   * Returns a new object of class '<em>Platform Data Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Data Model</em>'.
   * @generated
   */
  PlatformDataModel createPlatformDataModel();

  /**
   * Returns a new object of class '<em>Conceptual Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Element</em>'.
   * @generated
   */
  ConceptualElement createConceptualElement();

  /**
   * Returns a new object of class '<em>Conceptual Composable Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Composable Element</em>'.
   * @generated
   */
  ConceptualComposableElement createConceptualComposableElement();

  /**
   * Returns a new object of class '<em>Conceptual Basis Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Basis Entity</em>'.
   * @generated
   */
  ConceptualBasisEntity createConceptualBasisEntity();

  /**
   * Returns a new object of class '<em>Conceptual Domain</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Domain</em>'.
   * @generated
   */
  ConceptualDomain createConceptualDomain();

  /**
   * Returns a new object of class '<em>Conceptual Observable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Observable</em>'.
   * @generated
   */
  ConceptualObservable createConceptualObservable();

  /**
   * Returns a new object of class '<em>Conceptual Characteristic</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Characteristic</em>'.
   * @generated
   */
  ConceptualCharacteristic createConceptualCharacteristic();

  /**
   * Returns a new object of class '<em>Conceptual Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Entity</em>'.
   * @generated
   */
  ConceptualEntity createConceptualEntity();

  /**
   * Returns a new object of class '<em>Conceptual Composition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Composition</em>'.
   * @generated
   */
  ConceptualComposition createConceptualComposition();

  /**
   * Returns a new object of class '<em>Conceptual Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Association</em>'.
   * @generated
   */
  ConceptualAssociation createConceptualAssociation();

  /**
   * Returns a new object of class '<em>Conceptual Participant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Participant</em>'.
   * @generated
   */
  ConceptualParticipant createConceptualParticipant();

  /**
   * Returns a new object of class '<em>Conceptual Path Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Path Node</em>'.
   * @generated
   */
  ConceptualPathNode createConceptualPathNode();

  /**
   * Returns a new object of class '<em>Conceptual Participant Path Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Participant Path Node</em>'.
   * @generated
   */
  ConceptualParticipantPathNode createConceptualParticipantPathNode();

  /**
   * Returns a new object of class '<em>Conceptual Characteristic Path Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Characteristic Path Node</em>'.
   * @generated
   */
  ConceptualCharacteristicPathNode createConceptualCharacteristicPathNode();

  /**
   * Returns a new object of class '<em>Conceptual View</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual View</em>'.
   * @generated
   */
  ConceptualView createConceptualView();

  /**
   * Returns a new object of class '<em>Conceptual Query</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Query</em>'.
   * @generated
   */
  ConceptualQuery createConceptualQuery();

  /**
   * Returns a new object of class '<em>Conceptual Composite Query</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Composite Query</em>'.
   * @generated
   */
  ConceptualCompositeQuery createConceptualCompositeQuery();

  /**
   * Returns a new object of class '<em>Conceptual Query Composition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conceptual Query Composition</em>'.
   * @generated
   */
  ConceptualQueryComposition createConceptualQueryComposition();

  /**
   * Returns a new object of class '<em>Logical Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Element</em>'.
   * @generated
   */
  LogicalElement createLogicalElement();

  /**
   * Returns a new object of class '<em>Logical Unit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Unit</em>'.
   * @generated
   */
  LogicalUnit createLogicalUnit();

  /**
   * Returns a new object of class '<em>Logical Conversion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Conversion</em>'.
   * @generated
   */
  LogicalConversion createLogicalConversion();

  /**
   * Returns a new object of class '<em>Logical Affine Conversion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Affine Conversion</em>'.
   * @generated
   */
  LogicalAffineConversion createLogicalAffineConversion();

  /**
   * Returns a new object of class '<em>Logical Value Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Value Type</em>'.
   * @generated
   */
  LogicalValueType createLogicalValueType();

  /**
   * Returns a new object of class '<em>Logical String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical String</em>'.
   * @generated
   */
  LogicalString createLogicalString();

  /**
   * Returns a new object of class '<em>Logical Character</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Character</em>'.
   * @generated
   */
  LogicalCharacter createLogicalCharacter();

  /**
   * Returns a new object of class '<em>Logical Boolean</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Boolean</em>'.
   * @generated
   */
  LogicalBoolean createLogicalBoolean();

  /**
   * Returns a new object of class '<em>Logical Numeric</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Numeric</em>'.
   * @generated
   */
  LogicalNumeric createLogicalNumeric();

  /**
   * Returns a new object of class '<em>Logical Integer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Integer</em>'.
   * @generated
   */
  LogicalInteger createLogicalInteger();

  /**
   * Returns a new object of class '<em>Logical Natural</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Natural</em>'.
   * @generated
   */
  LogicalNatural createLogicalNatural();

  /**
   * Returns a new object of class '<em>Logical Real</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Real</em>'.
   * @generated
   */
  LogicalReal createLogicalReal();

  /**
   * Returns a new object of class '<em>Logical Non Negative Real</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Non Negative Real</em>'.
   * @generated
   */
  LogicalNonNegativeReal createLogicalNonNegativeReal();

  /**
   * Returns a new object of class '<em>Logical Enumerated</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Enumerated</em>'.
   * @generated
   */
  LogicalEnumerated createLogicalEnumerated();

  /**
   * Returns a new object of class '<em>Taxonomy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Taxonomy</em>'.
   * @generated
   */
  Taxonomy createTaxonomy();

  /**
   * Returns a new object of class '<em>Logical Enumerated Base</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Enumerated Base</em>'.
   * @generated
   */
  LogicalEnumeratedBase createLogicalEnumeratedBase();

  /**
   * Returns a new object of class '<em>Logical Enumerated Set</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Enumerated Set</em>'.
   * @generated
   */
  LogicalEnumeratedSet createLogicalEnumeratedSet();

  /**
   * Returns a new object of class '<em>Logical Enumeration Label</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Enumeration Label</em>'.
   * @generated
   */
  LogicalEnumerationLabel createLogicalEnumerationLabel();

  /**
   * Returns a new object of class '<em>Logical Coordinate System</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Coordinate System</em>'.
   * @generated
   */
  LogicalCoordinateSystem createLogicalCoordinateSystem();

  /**
   * Returns a new object of class '<em>Logical Coordinate System Axis</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Coordinate System Axis</em>'.
   * @generated
   */
  LogicalCoordinateSystemAxis createLogicalCoordinateSystemAxis();

  /**
   * Returns a new object of class '<em>Logical Abstract Measurement System</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Abstract Measurement System</em>'.
   * @generated
   */
  LogicalAbstractMeasurementSystem createLogicalAbstractMeasurementSystem();

  /**
   * Returns a new object of class '<em>Logical Standard Measurement System</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Standard Measurement System</em>'.
   * @generated
   */
  LogicalStandardMeasurementSystem createLogicalStandardMeasurementSystem();

  /**
   * Returns a new object of class '<em>Logical Landmark</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Landmark</em>'.
   * @generated
   */
  LogicalLandmark createLogicalLandmark();

  /**
   * Returns a new object of class '<em>Logical Measurement System</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Measurement System</em>'.
   * @generated
   */
  LogicalMeasurementSystem createLogicalMeasurementSystem();

  /**
   * Returns a new object of class '<em>Logical Measurement System Axis</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Measurement System Axis</em>'.
   * @generated
   */
  LogicalMeasurementSystemAxis createLogicalMeasurementSystemAxis();

  /**
   * Returns a new object of class '<em>Logical Reference Point</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Reference Point</em>'.
   * @generated
   */
  LogicalReferencePoint createLogicalReferencePoint();

  /**
   * Returns a new object of class '<em>Logical Reference Point Part</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Reference Point Part</em>'.
   * @generated
   */
  LogicalReferencePointPart createLogicalReferencePointPart();

  /**
   * Returns a new object of class '<em>Logical Value Type Unit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Value Type Unit</em>'.
   * @generated
   */
  LogicalValueTypeUnit createLogicalValueTypeUnit();

  /**
   * Returns a new object of class '<em>Logical Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Constraint</em>'.
   * @generated
   */
  LogicalConstraint createLogicalConstraint();

  /**
   * Returns a new object of class '<em>Logical Integer Range Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Integer Range Constraint</em>'.
   * @generated
   */
  LogicalIntegerRangeConstraint createLogicalIntegerRangeConstraint();

  /**
   * Returns a new object of class '<em>Logical Real Range Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Real Range Constraint</em>'.
   * @generated
   */
  LogicalRealRangeConstraint createLogicalRealRangeConstraint();

  /**
   * Returns a new object of class '<em>Logical String Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical String Constraint</em>'.
   * @generated
   */
  LogicalStringConstraint createLogicalStringConstraint();

  /**
   * Returns a new object of class '<em>Logical Regular Expression Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Regular Expression Constraint</em>'.
   * @generated
   */
  LogicalRegularExpressionConstraint createLogicalRegularExpressionConstraint();

  /**
   * Returns a new object of class '<em>Logical Fixed Length String Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Fixed Length String Constraint</em>'.
   * @generated
   */
  LogicalFixedLengthStringConstraint createLogicalFixedLengthStringConstraint();

  /**
   * Returns a new object of class '<em>Logical Enumeration Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Enumeration Constraint</em>'.
   * @generated
   */
  LogicalEnumerationConstraint createLogicalEnumerationConstraint();

  /**
   * Returns a new object of class '<em>Logical Measurement Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Measurement Constraint</em>'.
   * @generated
   */
  LogicalMeasurementConstraint createLogicalMeasurementConstraint();

  /**
   * Returns a new object of class '<em>Logical Measurement System Conversion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Measurement System Conversion</em>'.
   * @generated
   */
  LogicalMeasurementSystemConversion createLogicalMeasurementSystemConversion();

  /**
   * Returns a new object of class '<em>Logical Measurement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Measurement</em>'.
   * @generated
   */
  LogicalMeasurement createLogicalMeasurement();

  /**
   * Returns a new object of class '<em>Logical Measurement Axis</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Measurement Axis</em>'.
   * @generated
   */
  LogicalMeasurementAxis createLogicalMeasurementAxis();

  /**
   * Returns a new object of class '<em>Logical Measurement Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Measurement Attribute</em>'.
   * @generated
   */
  LogicalMeasurementAttribute createLogicalMeasurementAttribute();

  /**
   * Returns a new object of class '<em>Logical Measurement Conversion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Measurement Conversion</em>'.
   * @generated
   */
  LogicalMeasurementConversion createLogicalMeasurementConversion();

  /**
   * Returns a new object of class '<em>Logical Composable Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Composable Element</em>'.
   * @generated
   */
  LogicalComposableElement createLogicalComposableElement();

  /**
   * Returns a new object of class '<em>Logical Characteristic</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Characteristic</em>'.
   * @generated
   */
  LogicalCharacteristic createLogicalCharacteristic();

  /**
   * Returns a new object of class '<em>Logical Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Entity</em>'.
   * @generated
   */
  LogicalEntity createLogicalEntity();

  /**
   * Returns a new object of class '<em>Logical Composition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Composition</em>'.
   * @generated
   */
  LogicalComposition createLogicalComposition();

  /**
   * Returns a new object of class '<em>Logical Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Association</em>'.
   * @generated
   */
  LogicalAssociation createLogicalAssociation();

  /**
   * Returns a new object of class '<em>Logical Participant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Participant</em>'.
   * @generated
   */
  LogicalParticipant createLogicalParticipant();

  /**
   * Returns a new object of class '<em>Logical Path Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Path Node</em>'.
   * @generated
   */
  LogicalPathNode createLogicalPathNode();

  /**
   * Returns a new object of class '<em>Logical Participant Path Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Participant Path Node</em>'.
   * @generated
   */
  LogicalParticipantPathNode createLogicalParticipantPathNode();

  /**
   * Returns a new object of class '<em>Logical Characteristic Path Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Characteristic Path Node</em>'.
   * @generated
   */
  LogicalCharacteristicPathNode createLogicalCharacteristicPathNode();

  /**
   * Returns a new object of class '<em>Logical View</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical View</em>'.
   * @generated
   */
  LogicalView createLogicalView();

  /**
   * Returns a new object of class '<em>Logical Query</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Query</em>'.
   * @generated
   */
  LogicalQuery createLogicalQuery();

  /**
   * Returns a new object of class '<em>Logical Composite Query</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Composite Query</em>'.
   * @generated
   */
  LogicalCompositeQuery createLogicalCompositeQuery();

  /**
   * Returns a new object of class '<em>Logical Query Composition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Query Composition</em>'.
   * @generated
   */
  LogicalQueryComposition createLogicalQueryComposition();

  /**
   * Returns a new object of class '<em>Platform Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Element</em>'.
   * @generated
   */
  PlatformElement createPlatformElement();

  /**
   * Returns a new object of class '<em>Platform Composable Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Composable Element</em>'.
   * @generated
   */
  PlatformComposableElement createPlatformComposableElement();

  /**
   * Returns a new object of class '<em>Platform Data Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Data Type</em>'.
   * @generated
   */
  PlatformDataType createPlatformDataType();

  /**
   * Returns a new object of class '<em>Platform Primitive</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Primitive</em>'.
   * @generated
   */
  PlatformPrimitive createPlatformPrimitive();

  /**
   * Returns a new object of class '<em>Platform Boolean</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Boolean</em>'.
   * @generated
   */
  PlatformBoolean createPlatformBoolean();

  /**
   * Returns a new object of class '<em>Platform Octet</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Octet</em>'.
   * @generated
   */
  PlatformOctet createPlatformOctet();

  /**
   * Returns a new object of class '<em>Platform Char</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Char</em>'.
   * @generated
   */
  PlatformChar createPlatformChar();

  /**
   * Returns a new object of class '<em>Platform String Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform String Type</em>'.
   * @generated
   */
  PlatformStringType createPlatformStringType();

  /**
   * Returns a new object of class '<em>Platform String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform String</em>'.
   * @generated
   */
  PlatformString createPlatformString();

  /**
   * Returns a new object of class '<em>Platform Bounded String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Bounded String</em>'.
   * @generated
   */
  PlatformBoundedString createPlatformBoundedString();

  /**
   * Returns a new object of class '<em>Platform Char Array</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Char Array</em>'.
   * @generated
   */
  PlatformCharArray createPlatformCharArray();

  /**
   * Returns a new object of class '<em>Platform Enumeration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Enumeration</em>'.
   * @generated
   */
  PlatformEnumeration createPlatformEnumeration();

  /**
   * Returns a new object of class '<em>Platform Number</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Number</em>'.
   * @generated
   */
  PlatformNumber createPlatformNumber();

  /**
   * Returns a new object of class '<em>Platform Integer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Integer</em>'.
   * @generated
   */
  PlatformInteger createPlatformInteger();

  /**
   * Returns a new object of class '<em>Platform Short</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Short</em>'.
   * @generated
   */
  PlatformShort createPlatformShort();

  /**
   * Returns a new object of class '<em>Platform Long</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Long</em>'.
   * @generated
   */
  PlatformLong createPlatformLong();

  /**
   * Returns a new object of class '<em>Platform Long Long</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Long Long</em>'.
   * @generated
   */
  PlatformLongLong createPlatformLongLong();

  /**
   * Returns a new object of class '<em>Platform Real</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Real</em>'.
   * @generated
   */
  PlatformReal createPlatformReal();

  /**
   * Returns a new object of class '<em>Platform Double</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Double</em>'.
   * @generated
   */
  PlatformDouble createPlatformDouble();

  /**
   * Returns a new object of class '<em>Platform Long Double</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Long Double</em>'.
   * @generated
   */
  PlatformLongDouble createPlatformLongDouble();

  /**
   * Returns a new object of class '<em>Platform Float</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Float</em>'.
   * @generated
   */
  PlatformFloat createPlatformFloat();

  /**
   * Returns a new object of class '<em>Platform Fixed</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Fixed</em>'.
   * @generated
   */
  PlatformFixed createPlatformFixed();

  /**
   * Returns a new object of class '<em>Platform Unsigned Integer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Unsigned Integer</em>'.
   * @generated
   */
  PlatformUnsignedInteger createPlatformUnsignedInteger();

  /**
   * Returns a new object of class '<em>Platform UShort</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform UShort</em>'.
   * @generated
   */
  PlatformUShort createPlatformUShort();

  /**
   * Returns a new object of class '<em>Platform ULong</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform ULong</em>'.
   * @generated
   */
  PlatformULong createPlatformULong();

  /**
   * Returns a new object of class '<em>Platform ULong Long</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform ULong Long</em>'.
   * @generated
   */
  PlatformULongLong createPlatformULongLong();

  /**
   * Returns a new object of class '<em>Platform Sequence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Sequence</em>'.
   * @generated
   */
  PlatformSequence createPlatformSequence();

  /**
   * Returns a new object of class '<em>Platform Array</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Array</em>'.
   * @generated
   */
  PlatformArray createPlatformArray();

  /**
   * Returns a new object of class '<em>Platform Struct</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Struct</em>'.
   * @generated
   */
  PlatformStruct createPlatformStruct();

  /**
   * Returns a new object of class '<em>Platform Struct Member</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Struct Member</em>'.
   * @generated
   */
  PlatformStructMember createPlatformStructMember();

  /**
   * Returns a new object of class '<em>Platform Characteristic</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Characteristic</em>'.
   * @generated
   */
  PlatformCharacteristic createPlatformCharacteristic();

  /**
   * Returns a new object of class '<em>Platform Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Entity</em>'.
   * @generated
   */
  PlatformEntity createPlatformEntity();

  /**
   * Returns a new object of class '<em>Platform Composition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Composition</em>'.
   * @generated
   */
  PlatformComposition createPlatformComposition();

  /**
   * Returns a new object of class '<em>Platform Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Association</em>'.
   * @generated
   */
  PlatformAssociation createPlatformAssociation();

  /**
   * Returns a new object of class '<em>Platform Participant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Participant</em>'.
   * @generated
   */
  PlatformParticipant createPlatformParticipant();

  /**
   * Returns a new object of class '<em>Platform Path Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Path Node</em>'.
   * @generated
   */
  PlatformPathNode createPlatformPathNode();

  /**
   * Returns a new object of class '<em>Platform Participant Path Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Participant Path Node</em>'.
   * @generated
   */
  PlatformParticipantPathNode createPlatformParticipantPathNode();

  /**
   * Returns a new object of class '<em>Platform Characteristic Path Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Characteristic Path Node</em>'.
   * @generated
   */
  PlatformCharacteristicPathNode createPlatformCharacteristicPathNode();

  /**
   * Returns a new object of class '<em>Platform View</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform View</em>'.
   * @generated
   */
  PlatformView createPlatformView();

  /**
   * Returns a new object of class '<em>Platform Query</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Query</em>'.
   * @generated
   */
  PlatformQuery createPlatformQuery();

  /**
   * Returns a new object of class '<em>Platform Composite Query</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Composite Query</em>'.
   * @generated
   */
  PlatformCompositeQuery createPlatformCompositeQuery();

  /**
   * Returns a new object of class '<em>Platform Query Composition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Platform Query Composition</em>'.
   * @generated
   */
  PlatformQueryComposition createPlatformQueryComposition();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  UddlPackage getUddlPackage();

} //UddlFactory
