/*
 * generated by Xtext 2.32.0
 */
/*
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UddlStandaloneSetup extends UddlStandaloneSetupGenerated {

	public static void doSetup() {
		new UddlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
