/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl.impl;

import com.epistimis.uddl.uddl.ConceptualCharacteristic;
import com.epistimis.uddl.uddl.UddlPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Conceptual Characteristic</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.uddl.impl.ConceptualCharacteristicImpl#getRolename <em>Rolename</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.impl.ConceptualCharacteristicImpl#getLowerBound <em>Lower Bound</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.impl.ConceptualCharacteristicImpl#getUpperBound <em>Upper Bound</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.impl.ConceptualCharacteristicImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.impl.ConceptualCharacteristicImpl#getSpecializes <em>Specializes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConceptualCharacteristicImpl extends MinimalEObjectImpl.Container implements ConceptualCharacteristic
{
  /**
   * The default value of the '{@link #getRolename() <em>Rolename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRolename()
   * @generated
   * @ordered
   */
  protected static final String ROLENAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRolename() <em>Rolename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRolename()
   * @generated
   * @ordered
   */
  protected String rolename = ROLENAME_EDEFAULT;

  /**
   * The default value of the '{@link #getLowerBound() <em>Lower Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLowerBound()
   * @generated
   * @ordered
   */
  protected static final int LOWER_BOUND_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLowerBound() <em>Lower Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLowerBound()
   * @generated
   * @ordered
   */
  protected int lowerBound = LOWER_BOUND_EDEFAULT;

  /**
   * The default value of the '{@link #getUpperBound() <em>Upper Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUpperBound()
   * @generated
   * @ordered
   */
  protected static final int UPPER_BOUND_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getUpperBound() <em>Upper Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUpperBound()
   * @generated
   * @ordered
   */
  protected int upperBound = UPPER_BOUND_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The cached value of the '{@link #getSpecializes() <em>Specializes</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpecializes()
   * @generated
   * @ordered
   */
  protected ConceptualCharacteristic specializes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConceptualCharacteristicImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UddlPackage.Literals.CONCEPTUAL_CHARACTERISTIC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRolename()
  {
    return rolename;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRolename(String newRolename)
  {
    String oldRolename = rolename;
    rolename = newRolename;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UddlPackage.CONCEPTUAL_CHARACTERISTIC__ROLENAME, oldRolename, rolename));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getLowerBound()
  {
    return lowerBound;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLowerBound(int newLowerBound)
  {
    int oldLowerBound = lowerBound;
    lowerBound = newLowerBound;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UddlPackage.CONCEPTUAL_CHARACTERISTIC__LOWER_BOUND, oldLowerBound, lowerBound));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getUpperBound()
  {
    return upperBound;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUpperBound(int newUpperBound)
  {
    int oldUpperBound = upperBound;
    upperBound = newUpperBound;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UddlPackage.CONCEPTUAL_CHARACTERISTIC__UPPER_BOUND, oldUpperBound, upperBound));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UddlPackage.CONCEPTUAL_CHARACTERISTIC__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConceptualCharacteristic getSpecializes()
  {
    if (specializes != null && specializes.eIsProxy())
    {
      InternalEObject oldSpecializes = (InternalEObject)specializes;
      specializes = (ConceptualCharacteristic)eResolveProxy(oldSpecializes);
      if (specializes != oldSpecializes)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, UddlPackage.CONCEPTUAL_CHARACTERISTIC__SPECIALIZES, oldSpecializes, specializes));
      }
    }
    return specializes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConceptualCharacteristic basicGetSpecializes()
  {
    return specializes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSpecializes(ConceptualCharacteristic newSpecializes)
  {
    ConceptualCharacteristic oldSpecializes = specializes;
    specializes = newSpecializes;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UddlPackage.CONCEPTUAL_CHARACTERISTIC__SPECIALIZES, oldSpecializes, specializes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__ROLENAME:
        return getRolename();
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__LOWER_BOUND:
        return getLowerBound();
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__UPPER_BOUND:
        return getUpperBound();
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__DESCRIPTION:
        return getDescription();
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__SPECIALIZES:
        if (resolve) return getSpecializes();
        return basicGetSpecializes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__ROLENAME:
        setRolename((String)newValue);
        return;
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__LOWER_BOUND:
        setLowerBound((Integer)newValue);
        return;
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__UPPER_BOUND:
        setUpperBound((Integer)newValue);
        return;
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__SPECIALIZES:
        setSpecializes((ConceptualCharacteristic)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__ROLENAME:
        setRolename(ROLENAME_EDEFAULT);
        return;
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__LOWER_BOUND:
        setLowerBound(LOWER_BOUND_EDEFAULT);
        return;
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__UPPER_BOUND:
        setUpperBound(UPPER_BOUND_EDEFAULT);
        return;
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__SPECIALIZES:
        setSpecializes((ConceptualCharacteristic)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__ROLENAME:
        return ROLENAME_EDEFAULT == null ? rolename != null : !ROLENAME_EDEFAULT.equals(rolename);
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__LOWER_BOUND:
        return lowerBound != LOWER_BOUND_EDEFAULT;
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__UPPER_BOUND:
        return upperBound != UPPER_BOUND_EDEFAULT;
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case UddlPackage.CONCEPTUAL_CHARACTERISTIC__SPECIALIZES:
        return specializes != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (rolename: ");
    result.append(rolename);
    result.append(", lowerBound: ");
    result.append(lowerBound);
    result.append(", upperBound: ");
    result.append(upperBound);
    result.append(", description: ");
    result.append(description);
    result.append(')');
    return result.toString();
  }

} //ConceptualCharacteristicImpl
