/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl.impl;

import com.epistimis.uddl.uddl.LogicalDataModel;
import com.epistimis.uddl.uddl.LogicalElement;
import com.epistimis.uddl.uddl.UddlPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Logical Data Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.uddl.impl.LogicalDataModelImpl#getElement <em>Element</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.impl.LogicalDataModelImpl#getLdm <em>Ldm</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LogicalDataModelImpl extends UddlElementImpl implements LogicalDataModel
{
  /**
   * The cached value of the '{@link #getElement() <em>Element</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElement()
   * @generated
   * @ordered
   */
  protected EList<LogicalElement> element;

  /**
   * The cached value of the '{@link #getLdm() <em>Ldm</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLdm()
   * @generated
   * @ordered
   */
  protected EList<LogicalDataModel> ldm;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LogicalDataModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UddlPackage.Literals.LOGICAL_DATA_MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LogicalElement> getElement()
  {
    if (element == null)
    {
      element = new EObjectContainmentEList<LogicalElement>(LogicalElement.class, this, UddlPackage.LOGICAL_DATA_MODEL__ELEMENT);
    }
    return element;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LogicalDataModel> getLdm()
  {
    if (ldm == null)
    {
      ldm = new EObjectContainmentEList<LogicalDataModel>(LogicalDataModel.class, this, UddlPackage.LOGICAL_DATA_MODEL__LDM);
    }
    return ldm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case UddlPackage.LOGICAL_DATA_MODEL__ELEMENT:
        return ((InternalEList<?>)getElement()).basicRemove(otherEnd, msgs);
      case UddlPackage.LOGICAL_DATA_MODEL__LDM:
        return ((InternalEList<?>)getLdm()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UddlPackage.LOGICAL_DATA_MODEL__ELEMENT:
        return getElement();
      case UddlPackage.LOGICAL_DATA_MODEL__LDM:
        return getLdm();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UddlPackage.LOGICAL_DATA_MODEL__ELEMENT:
        getElement().clear();
        getElement().addAll((Collection<? extends LogicalElement>)newValue);
        return;
      case UddlPackage.LOGICAL_DATA_MODEL__LDM:
        getLdm().clear();
        getLdm().addAll((Collection<? extends LogicalDataModel>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UddlPackage.LOGICAL_DATA_MODEL__ELEMENT:
        getElement().clear();
        return;
      case UddlPackage.LOGICAL_DATA_MODEL__LDM:
        getLdm().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UddlPackage.LOGICAL_DATA_MODEL__ELEMENT:
        return element != null && !element.isEmpty();
      case UddlPackage.LOGICAL_DATA_MODEL__LDM:
        return ldm != null && !ldm.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //LogicalDataModelImpl
