/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl.impl;

import com.epistimis.uddl.uddl.LogicalEnumerationConstraint;
import com.epistimis.uddl.uddl.LogicalEnumerationLabel;
import com.epistimis.uddl.uddl.UddlPackage;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Logical Enumeration Constraint</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.uddl.impl.LogicalEnumerationConstraintImpl#getAllowedValue <em>Allowed Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LogicalEnumerationConstraintImpl extends LogicalConstraintImpl implements LogicalEnumerationConstraint
{
  /**
   * The cached value of the '{@link #getAllowedValue() <em>Allowed Value</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAllowedValue()
   * @generated
   * @ordered
   */
  protected EList<LogicalEnumerationLabel> allowedValue;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LogicalEnumerationConstraintImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UddlPackage.Literals.LOGICAL_ENUMERATION_CONSTRAINT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LogicalEnumerationLabel> getAllowedValue()
  {
    if (allowedValue == null)
    {
      allowedValue = new EObjectResolvingEList<LogicalEnumerationLabel>(LogicalEnumerationLabel.class, this, UddlPackage.LOGICAL_ENUMERATION_CONSTRAINT__ALLOWED_VALUE);
    }
    return allowedValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UddlPackage.LOGICAL_ENUMERATION_CONSTRAINT__ALLOWED_VALUE:
        return getAllowedValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UddlPackage.LOGICAL_ENUMERATION_CONSTRAINT__ALLOWED_VALUE:
        getAllowedValue().clear();
        getAllowedValue().addAll((Collection<? extends LogicalEnumerationLabel>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UddlPackage.LOGICAL_ENUMERATION_CONSTRAINT__ALLOWED_VALUE:
        getAllowedValue().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UddlPackage.LOGICAL_ENUMERATION_CONSTRAINT__ALLOWED_VALUE:
        return allowedValue != null && !allowedValue.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //LogicalEnumerationConstraintImpl
