/**
 * generated by Xtext 2.32.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl.impl;

import com.epistimis.uddl.uddl.PlatformULongLong;
import com.epistimis.uddl.uddl.UddlPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Platform ULong Long</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PlatformULongLongImpl extends PlatformUnsignedIntegerImpl implements PlatformULongLong
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PlatformULongLongImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UddlPackage.Literals.PLATFORM_ULONG_LONG;
  }

} //PlatformULongLongImpl
