name: UDDLTest Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build Chain
    - uses: ginxo/github-action-build-chain@BXMSPROD-1025
      with:
        definition-file: 'https://github.com/prince4God/uddlquery/blob/main/.github/workflows/uddlquery.yml'
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: Build with Maven
      run: mvn -B package --file pom.xml
